name: "Test"

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Model Name"
        default: "big-pickle"
        type: string
      number:
        description: "Issue Number"
        default: "1"
        type: string
      instructions:
        description: "Instructions"
        type: string
  #push:
  #  branches: [main, master]
  #  paths:
  #    - ".github/workflows/test.yaml"
  #    - "src/**"
  #    - "action.yml"
  #    - "package*.json"
  #    - "*config.*"
  #pull_request:
  #  branches: [main, master]
  #  paths: *paths

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  number: ${{ inputs.number || '1' }}

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      issues: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        if: ${{ !github.event.act }}
        continue-on-error: true
        run: env

      - name: "Debug"
        continue-on-error: true
        run: |
          ls -lah .

      - name: "Setup Node"
        if: ${{ !github.event.act }}
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "Install & Build"
        if: ${{ !github.event.act }}
        run: |
          npm ci

      #- name: "Create App Token"
      #  id: app
      #  uses: actions/create-github-app-token@v3
      #  with:
      #    client-id: ${{ vars.APP_CLIENT_ID }}
      #    private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "Test Local Action"
        id: issue
        uses: ./
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PROVIDER_API_KEY: ${{ secrets.PROVIDER_API_KEY }}
        with:
          model: ${{ inputs.model || 'big-pickle' }}
          instructions: ${{ inputs.instructions }}
          url: https://raw.githubusercontent.com/cssnr/ai-issue-action/refs/heads/master/.github/instructions/test.md
          #path: .github/instructions/test.md
          max_tokens: 1024
          number: ${{ !github.event.act && env.number || '' }}
          #head: "This is an initial response provided by AI."
          tail: |
            _Response generated by the [AI Issue Action](https://github.com/cssnr/ai-issue-action)._
          #token: ${{ steps.app.outputs.token }}
          #token: ${{ SECRETS.APP_TOKEN }}

      - name: "Echo Outputs"
        env:
          text: ${{ steps.issue.outputs.text }}
          reasoningText: ${{ steps.issue.outputs.reasoningText }}
          usage: ${{ steps.issue.outputs.usage }}
          comment: ${{ steps.issue.outputs.comment }}
        run: |
          echo "text: ${text}"
          echo "reasoningText: ${reasoningText}"
          echo "${usage}" | jq
          echo "finishReason: ${{ steps.issue.outputs.finishReason }}"
          #echo "${comment}" | jq
          echo "commentId: ${{ steps.issue.outputs.commentId }}"
          echo "commentUrl: ${{ steps.issue.outputs.commentUrl }}"

      #- name: "Validate Outputs"
      #  if: ${{ !github.event.act }}
      #  uses: cssnr/validate-outputs-action@master
      #  with:
      #    outputs: ${{ toJSON(steps.issue.outputs) }}
      #    data: |
      #      sha: ${{ github.sha }}
